import { AuthProvider } from '@/context/AuthContext';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center gap-6 px-6 py-3 bg-gray-900 text-white text-sm border-b border-gray-800">
          <a href="/" className="font-bold">Vesania</a>
          <a href="/play" className="text-gray-300 hover:text-white">Play</a>
          <a href="/match" className="text-gray-300 hover:text-white">PvP</a>
          <a href="/api-docs" className="text-gray-300 hover:text-white">API Docs</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
